### ISSUE TITLE
Documentation for loading the compiled firmware onto the keyboard

### ISSUE THREAD

**Issue by freerobby** [chrisandreae/keyboard-firmware#1]
Is it possible to get instructions for loading a compiled firmware onto a Kinesis keyboard? Does this require burning a microchip or is the Kinesis chip reprogrammable?

**Comment by chrisandreae** [comment]
It requires building a board which replaces the Kinesis' original
microcontroller. The schematic in Eagle format and an example picture are
here: https://github.com/chrisandreae/keyboard-firmware/tree/public/schematic/KinesisAdvantage%20v2.5
