### ISSUE TITLE
hardware

### ISSUE THREAD

**Issue by PierreKircher** [chrisandreae/keyboard-firmware#10]
the schematic is there can i get a BOM for the components ? thank you

need it for the kinesis advantage 2.5 

thank you .. just a simple part id (on the board) corresponds to which real part to be bought thn mcu is a atm34u4 i know that but what about the rest ?

**Comment by chrisandreae** [comment]
I haven't made an exact BOM (probably should soon), but here are the things I bought specifically that might not be obvious from the schematic, and some example links to buy them on eBay:
- [24 pin 0.5mm pitch forward direction FFC ribbon cable](http://r.ebay.com/YnYqTP)
- [2 x 24 pin 0.5mm pitch FFC ribbon sockets](http://www.ebay.com/itm/10-pcs-FFC-FPC-24-pin-0-5mm-Pitch-Ribbon-Flat-Connector-Socket-Top-contact-/231575316632?pt=LH_DefaultDomain_0&hash=item35eaf6e898) 
- [3.6v Zener diodes for USB data lines](http://www.ebay.com/itm/100pcs-3-6V-0-5W-ZMM-1206-SMD-Zener-Diode-/171054799790?pt=LH_DefaultDomain_0&hash=item27d3a91bae)
- [2mm pin header to connect to existing Kinesis USB cable](http://www.ebay.com/itm/10pcs-1-X-40pin-2mm-breakaway-Male-header-for-Arduino-Prototype-Shield-DIY-/251074830562?pt=LH_DefaultDomain_0&hash=item3a7539e0e2)
- [Atmega32A-AU](http://r.ebay.com/qJ3YEH)

Other than that it's just some 0603 resistors and capacitors in various values as indicated on the schematic, a 16mhz crystal, a small electrolytic capacitor, and a 2.54mm pin header.
