### ISSUE TITLE
qtclient doesn't find a keyboard

### ISSUE THREAD

**Issue by xstable** [chrisandreae/keyboard-firmware#2]
I have installed those libusb-packeges:

libusbmuxd2
libusb-dev
libusb-1.0-0-dev
libusb-1.0-0
libusb-0.1-4
libhidapi-libusb0

than i run qmake, and make and start "KeyboardClient". But I see only the Message: No Keyboard selected, …but there is no Keyboard you could select.

If I start from CMD, I see the message: LIBUSBError when enumerating:  LIBUSB_ERROR_ACCESS

If I enter: 
sudo ./KeyboardClient 

I got:
Error: "/var/tmp/kdecache-suther" is owned by uid 1000 instead of uid 0.
LIBUSBError when enumerating:  LIBUSB_ERROR_INVALID_PARAM 

Seems to be kind of permission-problem. But I doesn't found any Group which I could add to my Sysadmin-Account to got this libusb permissions.

Please describe, which LIBUSB-Packege is need on (K)ubuntu 14.04 or how to start, to got this GUI to found Keyboards.

Thanks a lot.

**Comment by xstable** [comment]
Even the ruby-client doesn't work:

ruby ./keyboardcomm.rb 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- libusb (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from ./keyboardcomm.rb:1:in `<main>'

**Comment by chrisandreae** [comment]
If you're not running as root, you need to make sure that your user account has permissions to access the USB device. This typically involves creating a udev rule. See http://www.libusb.org/wiki/FAQ#CanIrunLinuxlibusbapplicationswithoutrootrootprivilege and http://stackoverflow.com/questions/13419691/accessing-a-usb-device-with-libusb-1-0-as-a-non-root-user for more details.
