### ISSUE TITLE
Will this work with an out of the box Kineses Advantage Pro Keyboard

### ISSUE THREAD

**Issue by MarkPearlCoZa** [chrisandreae/keyboard-firmware#9]
Hi,

While I'm a software developer, I haven't worked at this level before so I apologize upfront if this is a dumb or stupid question. 

Possibly my biggest complaint about the Kinesis is that I don't have an onscreen display for remapping keys. I have a Kinesis Advantage Pro Keyboard (Model #: KB510USB-met).

Would this firmware allow me to do this out of the box, or do I need to modify my keyboard before I can use the firmware? It was a little unclear to me after reading the readme.

Would appreciate any help/guidance.

**Comment by PierreKircher** [comment]
the gui is nice but it did not even work for my ergodox nor the kinesis 

you need the controller https://github.com/chrisandreae/keyboard-firmware/blob/public/schematic/KinesisAdvantage%20v2.5/photo1.jpg or use a teensy to break it out .. the firmware is for a other MCU then the org. kinesis 

nothing that voids the warrenty of the kinesis .. but still youd need to get your hands on the parts or have them manufactured

at the same point you might wana check the TMK firmware which brings more features

**Comment by MarkPearlCoZa** [comment]
@PierreKircher thank you for your explanation!
